export const subtitleData=[
    {
        id:1,
        startTime:'00',
        endTime:'00',
        startSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
        endSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
    },
    {
        id:2,
        startTime:'00',
        endTime:'00',
        startSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
        endSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
    },
    {
        id:3,
        startTime:'00',
        endTime:'00',
        startSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
        endSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
    },
    {
        id:4,
        startTime:'00',
        endTime:'00',
        startSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
        endSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
    },
    {
        id:5,
        startTime:'00',
        endTime:'00',
        startSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
        endSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
    },
    {
        id:6,
        startTime:'00',
        endTime:'00',
        startSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
        endSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
    },
    {
        id:7,
        startTime:'00',
        endTime:'00',
        startSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
        endSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
    },
    {
        id:8,
        startTime:'00',
        endTime:'00',
        startSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
        endSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
    },
    {
        id:9,
        startTime:'00',
        endTime:'00',
        startSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
        endSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
    },
    {
        id:10,
        startTime:'00',
        endTime:'00',
        startSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
        endSubtitle:'Do sint aliqua do Lorem incididunt sint aliquip non Lorem quis id incididunt.',
    },
]